version: 2
updates:
  # Ansible Galaxy collections
  - package-ecosystem: "ansible"
    directory: "/ansible"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ansible"
    labels:
      - "dependencies"
      - "ansible"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "ci"
