---
collections:
  # Pin to specific versions for reproducible builds
  - name: kubernetes.core
    version: "6.2.0"
  - name: community.general
    version: "12.1.0"
  - name: ansible.posix
    version: "2.1.0"

roles:
  - name: geerlingguy.docker
    version: "7.4.1"
  - name: geerlingguy.pip
    version: "3.0.0"
